In [2]:
import numpy as np
import matplotlib.pyplot as plt
import common_functions as cf #My library of relevant functions
import tensorflow as tf #for loading mnist data
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split #to split into train/cv/test samples

Load the data:

In [10]:
DATA_URL = 'https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz'

path = tf.keras.utils.get_file('mnist.npz', DATA_URL)
with np.load(path) as data:
    x_train = data['x_train']
    y_train = data['y_train']
    x_test = data['x_test']
    y_test = data['y_test']
    
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


Re-shape

In [11]:
x_train = x_train.reshape((60000,28*28))
x_test = x_test.reshape((10000,28*28))

Set up the model

In [25]:
tf.random.set_seed(1234)  # applied to achieve consistent results
model = Sequential(
    [
        Dense(25, activation = 'relu',   name = "L1"),
        Dense(15, activation = 'relu', name = "L2"),
        Dense(10, activation = 'linear', name = "L3")
    ]
)

model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.0001),
)

Train the model

In [26]:
history = model.fit(
    x_train,y_train,
    epochs=500
)

Epoch 1/500
1875/1875 [==============================] - 4s 2ms/step - loss: 7.5008
Epoch 2/500
1875/1875 [==============================] - 4s 2ms/step - loss: 1.8131
Epoch 3/500
1875/1875 [==============================] - 4s 2ms/step - loss: 1.4837
Epoch 4/500
1875/1875 [==============================] - 4s 2ms/step - loss: 1.3168
Epoch 5/500
1875/1875 [==============================] - 4s 2ms/step - loss: 1.1969
Epoch 6/500
1875/1875 [==============================] - 4s 2ms/step - loss: 1.0850
Epoch 7/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.9685
Epoch 8/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.8732
Epoch 9/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.8038
Epoch 10/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.7498
Epoch 11/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.6980
Epoch 12/500
1875/1875 [==============================] - 4s 2ms/step - lo

1875/1875 [==============================] - 4s 2ms/step - loss: 0.1087
Epoch 98/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1080
Epoch 99/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1078
Epoch 100/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1072
Epoch 101/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1067
Epoch 102/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1060
Epoch 103/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1056
Epoch 104/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1045
Epoch 105/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1041
Epoch 106/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1034
Epoch 107/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1033
Epoch 108/500
1875/1875 [==============================] - 4s 2ms/step

1875/1875 [==============================] - 4s 2ms/step - loss: 0.0753
Epoch 193/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0742
Epoch 194/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0748
Epoch 195/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0751
Epoch 196/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0739
Epoch 197/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0739
Epoch 198/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0729
Epoch 199/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0742
Epoch 200/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0732
Epoch 201/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0731
Epoch 202/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0731
Epoch 203/500
1875/1875 [==============================] - 4s 2ms/st

1875/1875 [==============================] - 4s 2ms/step - loss: 0.0620
Epoch 288/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0632
Epoch 289/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0626
Epoch 290/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0614
Epoch 291/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0615
Epoch 292/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0622
Epoch 293/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0622
Epoch 294/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0609
Epoch 295/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0615
Epoch 296/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0624
Epoch 297/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0614
Epoch 298/500
1875/1875 [==============================] - 4s 2ms/st

1875/1875 [==============================] - 4s 2ms/step - loss: 0.0555
Epoch 383/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0554
Epoch 384/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0560
Epoch 385/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0554
Epoch 386/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0559
Epoch 387/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0558
Epoch 388/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0557
Epoch 389/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0553
Epoch 390/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0561
Epoch 391/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0552
Epoch 392/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0558
Epoch 393/500
1875/1875 [==============================] - 4s 2ms/st

1875/1875 [==============================] - 4s 2ms/step - loss: 0.0512
Epoch 478/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0515
Epoch 479/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0512
Epoch 480/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0510
Epoch 481/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0515
Epoch 482/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0510
Epoch 483/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0514
Epoch 484/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0505
Epoch 485/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0508
Epoch 486/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0515
Epoch 487/500
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0503
Epoch 488/500
1875/1875 [==============================] - 4s 2ms/st

In [27]:
l3 = model.get_layer("L3")
W3, b3 = l3.get_weights()

#Evaluate model performance
yhat = model.predict(x_test)
y_predict = np.argmax(yhat, axis=1)
model.evaluate(x_test, y_test)

#Get the overall accuracy of the model
test_accuracy = np.mean(y_predict == y_test)
print(test_accuracy)

#View the confusion matrix
confusion = tf.math.confusion_matrix(labels=y_test, predictions=y_predict, num_classes=10)
print(confusion)


313/313 [==============================] - 1s 1ms/step - loss: 0.8335
0.9319
tf.Tensor(
[[ 949    1    1    0    5    6    8    3    5    2]
 [   0 1114    9    0    1    3    2    0    5    1]
 [   4    7  965   14    6    4    5   13   14    0]
 [   1    1   28  918    1   29    0    7   17    8]
 [   3    4   12    0  909    3    6    8    7   30]
 [   5    2    4   18    3  830    9    2   12    7]
 [  12    5    4    0   11   23  890    1   12    0]
 [   3   11   24   14    8    5    0  939    3   21]
 [   5    6   14   21    8   25    4    5  881    5]
 [   4    5    1   12   33    9    1    7   13  924]], shape=(10, 10), dtype=int32)


Currently loss for test data is significantly higher for test data than training data - overfitting.

Add plot of loss history.